[project]
name = "smoothness-hpo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keras==3.0.0",
    "raise-utils>=2.5.2",
]
